export const FETCH_PHONES_START='FETCH_PHONES_START'
export const FETCH_PHONES_SUCCESS='FETCH_PHONES_SUCCESS'
export const FETCH_PHONES_FAILURE='FETCH_PHONES_FAILURE'

export const ADD_PHONE_TO_BASKET='ADD_PHONE_TO_BASKET'

export const REMOVE_PHONE_FROM_BASKET = 'REMOVE_PHONE_FROM_BASKET'
export const REMOVE_ELEMENT_FROM_BASKET = 'REMOVE_ELEMENT_FROM_BASKET'
